language: node_js
node_js:
  - 12

services:
  - docker
#building
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

#tagging
  - docker tag udagram-api-feed kemiamb/udagram-api-feed:v1
  - docker tag udagram-api-user kemiamb/udagram-api-user:v1
  - docker tag udagram-frontend kemiamb/udagram-frontend:v1
  - docker tag reverseproxy kemiamb/reverseproxy:v1

#pushing
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kemiamb/udagram-api-feed:v1
  - docker push kemiamb/udagram-api-user:v1
  - docker push kemiamb/udagram-frontend:v1
  - docker push kemiamb/reverseproxy:v1