apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    run: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-user
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: kemiamb/udagram-api-user:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
             name: env-secret
