apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    run: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: udagram-frontend
  template:
    metadata:
      labels:
        run: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: kemiamb/udagram-frontend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
